#!/usr/bin/env python3
"""SIM-002: directed per-instruction programs, checked against expectations
written by hand from the manual (never generated by the simulator).

Each test/isa/*.s carries checkpoints as full-line comments:

    ;@ r0=2c r1=64 z=1 i=0 sp=0101 m2003=44 m0100=hi(ret1)

meaning: when execution reaches the next instruction, the state must be this.
Values are hex; hi(LABEL)/lo(LABEL) are the bytes of a label's address.
The program runs on sim.nim through tools/simtrace; tools/lockstep.py runs the
same programs on the VHDL CPU (CPU-001), so the RTL meets the same numbers.

    python3 test/isa/run_isa.py [FILE.s ...]
"""

import glob
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
BUILD = os.path.join(ROOT, "build", "isa")
SIMTRACE = os.path.join(BUILD, "simtrace")


def build_simtrace():
    src = os.path.join(ROOT, "tools", "simtrace.nim")
    if os.path.exists(SIMTRACE) and os.path.getmtime(SIMTRACE) > max(
            os.path.getmtime(src), os.path.getmtime(os.path.join(ROOT, "tools", "sim.nim"))):
        return
    os.makedirs(BUILD, exist_ok=True)
    subprocess.run(["nim", "c", "-d:release", "--hints:off", "--warnings:off",
                    "--nimcache:" + os.path.join(BUILD, "nimcache"), "-o:" + SIMTRACE, src],
                   check=True, capture_output=True)


def run_one(path):
    name = os.path.splitext(os.path.basename(path))[0]
    obj = os.path.join(BUILD, name + ".o")
    mapf = os.path.join(BUILD, name + ".map")
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "as.py"), path, obj,
                        "0x1000,0x3000,0x5000", "--map=" + mapf], capture_output=True, text=True, cwd=BUILD)
    if r.returncode:
        return ["%s: does not assemble\n%s" % (name, r.stdout + r.stderr)]

    syms, lines = {}, []
    for ln in open(mapf):
        t = ln.split()
        if t[0] == "sym":
            syms[t[2]] = int(t[1], 16)
        elif t[0] == "line":
            lines.append((int(t[3]), int(t[1], 16)))
    lines.sort()

    def value(v):
        m = re.fullmatch(r"(hi|lo)\((\w+)\)", v)
        if m:
            a = syms[m.group(2)]
            return a >> 8 if m.group(1) == "hi" else a & 0xFF
        return int(v, 16)

    checks = []              # (address, {key: value}, source line)
    for n, text in enumerate(open(path), 1):
        if text.startswith(";@"):
            want = dict(kv.split("=") for kv in text[2:].split())
            after = [a for l, a in lines if l > n]
            if not after:
                return ["%s:%d: checkpoint after the last instruction" % (name, n)]
            checks.append((after[0], {k: value(v) for k, v in want.items()}, n))

    trace = subprocess.run([SIMTRACE, obj, "100000"], capture_output=True, text=True).stdout
    image = open(obj, "rb").read()
    mem = {0x1000 + i: b for i, b in enumerate(image)}
    pending = list(checks)                  # matched on the first visit to each address
    bad = []
    for ln in trace.splitlines():
        t = ln.split()
        if t[0] == "W":
            mem[int(t[1], 16)] = int(t[2], 16)
            continue
        if t[0] != "S":
            continue
        pc = int(t[1], 16)
        state = {"r0": int(t[2], 16), "r1": int(t[3], 16), "z": int(t[4]) & 1,
                 "i": int(t[4]) >> 1 & 1, "sp": int(t[5], 16)}
        for chk in [c for c in pending if c[0] == pc]:
            pending.remove(chk)
            _, want, n = chk
            for k, v in want.items():
                got = mem.get(int(k[1:], 16), 0) if k[0] == "m" else state[k]
                if got != v:
                    bad.append("%s:%d: %s = %02x, want %02x" % (name, n, k, got, v))
    for _, _, n in pending:
        bad.append("%s:%d: checkpoint never reached" % (name, n))
    return bad, len(checks)


def main():
    build_simtrace()
    files = sys.argv[1:] or sorted(glob.glob(os.path.join(HERE, "*.s")))
    total, bad = 0, []
    for f in files:
        r = run_one(f)
        if isinstance(r, list):
            bad += r
            continue
        b, n = r
        total += n
        bad += b
    for b in bad:
        print("FAIL", b)
    print("SIM-002: %d programs, %d checkpoints, %d failures" % (len(files), total, len(bad)))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
