#!/usr/bin/env python3
"""SIM-003: tools/as.py emits the manual's encoding for every mnemonic and
format, and rejects bad input with an error.

Every expected byte string below is written out by hand from the manual
(doc/CUPC8 Manual.md, section 3.4): the opcode byte is the 5-bit operation in
bits 7..3, bit 2 = immediate/indexed, bit 1 = Rb, bit 0 = Ra; addresses are
little-endian. Nothing here is generated by the assembler.

    python3 test/asm/test_asm.py
"""

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
AS = os.path.join(ROOT, "tools", "as.py")

# (source line, expected bytes)
GOLDEN = [
    # register format: op | 0 | Rb | Ra
    ("nop",              "80"),
    ("mov r0, r0",       "88"), ("mov r1, r0", "89"), ("mov r0, r1", "8a"), ("mov r1, r1", "8b"),
    ("push r0",          "90"), ("push r1", "92"),
    ("pop r0",           "98"), ("pop r1", "99"),
    ("eq r0, r1",        "02"), ("gt r1, r0", "09"), ("lt r1, r1", "13"),
    ("and r0, r1",       "1a"), ("or r1, r0", "21"), ("xor r0, r1", "32"), ("nor r1, r1", "3b"),
    ("add r0, r1",       "42"), ("sub r1, r0", "49"),
    ("shl r0, r1",       "62"), ("shr r1, r0", "69"),
    ("cli",              "c0"), ("sti", "c8"), ("wai", "f0"), ("halt", "f8"),
    ("tmr0 r1",          "e2"), ("tmr1 r0", "e8"), ("tmr1 r1", "ea"),   # TMR0/TMR1 Rb
    # immediate format: op | 1 | ? | Ra, imm
    ("mov r0, #0x12",    "8c 12"), ("mov r1, #255", "8d ff"),
    ("push #0x7f",       "94 7f"),
    ("eq r0, #1",        "04 01"), ("gt r1, #2", "0d 02"), ("lt r0, #3", "14 03"),
    ("and r1, #0x0f",    "1d 0f"), ("or r0, #0x80", "24 80"), ("xor r1, #0xaa", "35 aa"),
    ("nor r0, #0",       "3c 00"),
    ("add r1, #7",       "45 07"), ("sub r0, #9", "4c 09"),
    ("shl r1, #4",       "65 04"), ("shr r0, #1", "6c 01"),
    ("tmr0 #100",        "e4 64"), ("tmr1 #0x20", "ec 20"),
    # memory format: op | indexed | Rb | Ra, addr lo, addr hi
    ("ld r0, $1234",     "a0 34 12"), ("ld r1, $f000", "a1 00 f0"),
    ("ld r0, $2000+r1",  "a6 00 20"), ("ld r1, $abcd+r0", "a5 cd ab"),
    ("st $1234, r1",     "aa 34 12"), ("st $f000, r0", "a8 00 f0"),
    ("st $2000+r1, r0",  "ad 00 20"), ("st $2000+r0, r1", "ae 00 20"),
    ("ldd r1, $3000",    "71 00 30"), ("ldd r0, $3000+r1", "76 00 30"),
    ("std $3000, r1",    "7a 00 30"), ("std $3000+r1, r0", "7d 00 30"),
    # flow format: op, addr lo, addr hi
    ("b $e123",          "b0 23 e1"), ("bzf $0102", "b8 02 01"),
    # special register operands (manual 3.4, "Special register operands")
    ("push pch",         "96"), ("push pcl", "97"),
    ("pop pch",          "9e"), ("pop pcl", "9f"), ("pop f", "9c"),
]

# lines the assembler must refuse (non-zero exit)
REJECT = [
    "frob r0",                      # no such mnemonic
    "mov r2, r0",                   # no such register
    "mov r0, #256",                 # immediate out of range
    "ld r0, $10000",                # address out of range
    "b nowhere",                    # undefined label
    "ld r0, [missing]",             # undefined variable
]


def assemble(line):
    """Bytes for one instruction (after the 3-byte jump to main), or None."""
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "t.s")
        out = os.path.join(d, "t.o")
        with open(src, "w") as f:
            f.write("main:\n\t%s\n" % line)
        r = subprocess.run([sys.executable, AS, src, out, "0x1000,0x3000,0x5000"],
                           capture_output=True, text=True, cwd=d)
        if r.returncode != 0:
            return None
        data = open(out, "rb").read()
    code = data[3:]
    return code


# "db" and "resb" are directives only as the second token of a line: a
# %define, an address or a comment with those letters in it is code (as.py
# once took any line with a lower-case "db" in it for data, which is why
# kernel/api.inc wrote API_ST_DELETE as $10DB)
DIRECTIVE_WORDS = [
    ("%define ADDR $10db\n\tb ADDR",          "b0 db 10"),
    ("%define ADDR $10DB\n\tb ADDR",          "b0 db 10"),
    ("b $10db",                               "b0 db 10"),
    ("ld r0, $6fdb",                          "a0 db 6f"),
    ("mov r0, #1\t\t; a comment on db and resb", "8c 01"),
]


def assemble_data(src):
    """(code after the jump to main, data segment) for a whole source, or None."""
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "t.s")
        out = os.path.join(d, "t.o")
        with open(path, "w") as f:
            f.write(src)
        r = subprocess.run([sys.executable, AS, path, out, "0x1000,0x3000,0x5000"],
                           capture_output=True, text=True, cwd=d)
        if r.returncode != 0:
            return None
        data = open(out, "rb").read()
    return data[3:0x2000], data[0x2000:]


def main():
    bad = 0
    for line, want in DIRECTIVE_WORDS:
        want_b = bytes.fromhex(want)
        got = assemble(line)
        if got is None or got[:len(want_b)] != want_b:
            bad += 1
            print("FAIL %r: want %s got %s" % (line, want, "error" if got is None else got[:4].hex(" ")))
    # the directives themselves still work: data, bss and a variable in each
    got = assemble_data('greet db "hi"\nnums db 1, 2, 219\ncount: resb 2\nmain:\n'
                        '\tld r0, [nums+2]\n\tst [count+1], r0\n')
    want_code = bytes.fromhex("a0 05 30 a8 01 50")
    if got is None or got[0][:6] != want_code or got[1][:6] != b"hi\x00\x01\x02\xdb":
        bad += 1
        print("FAIL db and resb directives: got %s" % ("error" if got is None else
              got[0][:6].hex(" ") + " / " + got[1][:6].hex(" ")))

    for line, want in GOLDEN:
        want_b = bytes.fromhex(want)
        got = assemble(line)
        if got is None or got[:len(want_b)] != want_b or any(got[len(want_b):0x2000 - 3]):
            bad += 1
            print("FAIL %-20s want %s got %s" % (line, want, "error" if got is None else got[:4].hex(" ")))
    for line in REJECT:
        if assemble(line) is not None:
            bad += 1
            print("FAIL %-20s was accepted" % line)
    print("SIM-003: %d encodings, %d rejections, %d directive checks, %d failures" % (
        len(GOLDEN), len(REJECT), len(DIRECTIVE_WORDS) + 1, bad))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
