"""Run ngspice decks for the power checks, and report checks uniformly.

A deck is a string. `run()` writes it to build/power/<name>.cir with the
libraries included, runs ngspice in batch mode (PSpice compatibility on, for
the TI models) and returns the `.meas` results as a dict of floats.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "build", "power")
sys.path.insert(0, os.path.join(HERE, "models"))
import fetch  # noqa: E402

BEHAVIOURAL = os.path.join(HERE, "models", "behavioural.lib")


def lib(name):
    """Path of a library: 'behavioural' or a vendor model fetched by fetch.py."""
    return BEHAVIOURAL if name == "behavioural" else fetch.fetch(name)


def params(d):
    return " ".join("%s=%s" % (k, "%g" % v) for k, v in d.items())


def run(name, deck, libs=("behavioural",), timeout=900):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, ".spiceinit"), "w") as f:
        f.write("set ngbehavior=psa\nset num_threads=1\n")
    path = os.path.join(OUT, name + ".cir")
    includes = "".join(".include %s\n" % lib(n) for n in libs)
    with open(path, "w") as f:
        f.write("* %s (generated by hw/power)\n%s%s\n.end\n" % (name, includes, deck))
    proc = subprocess.run(["ngspice", "-b", path], cwd=OUT, capture_output=True, text=True, timeout=timeout)
    log = proc.stdout + proc.stderr
    with open(os.path.join(OUT, name + ".log"), "w") as f:
        f.write(log)
    meas = {}
    for m in re.finditer(r"^(\w+)\s+=\s+([-+0-9.eE]+)", log, re.M):
        meas[m.group(1).lower()] = float(m.group(2))
    failed = re.findall(r"^Error: measure\s+(\w+)", log, re.M)
    if proc.returncode or failed:
        sys.exit("ngspice %s failed (rc %d, measures %s); see %s" % (
            name, proc.returncode, failed, os.path.relpath(os.path.join(OUT, name + ".log"), ROOT)))
    return meas


def wave(name):
    """Columns written by `wrdata <name>.dat v1 v2 ...` in a deck: returns
    (time, [v1 samples], [v2 samples], ...)."""
    cols = None
    with open(os.path.join(OUT, name + ".dat")) as f:
        for line in f:
            vals = [float(x) for x in line.split()]
            if cols is None:
                cols = [[] for _ in range(len(vals) // 2 + 1)]
            cols[0].append(vals[0])
            for k in range(1, len(vals), 2):
                cols[(k + 1) // 2].append(vals[k])
    return cols


def at(t, v, when):
    """Linear interpolation of a waveform at time `when`."""
    for k in range(1, len(t)):
        if t[k] >= when:
            f = (when - t[k - 1]) / (t[k] - t[k - 1]) if t[k] > t[k - 1] else 0
            return v[k - 1] + f * (v[k] - v[k - 1])
    return v[-1]


class Checks:
    """Collects pass/fail lines: every check prints its number, limit and margin."""

    def __init__(self, title):
        self.failed = []
        print(title)

    def check(self, ident, what, value, limit, kind, unit="V", fmt="%.3f", need=0.0):
        """kind '>=' or '<='. Margin is how far inside the limit the value is;
        `need` is the margin required, as a fraction of the limit."""
        margin = value - limit if kind == ">=" else limit - value
        ok = margin >= need * abs(limit)
        rel = "" if not limit else " (%+.1f%%%s)" % (100 * margin / abs(limit),
                                                    ", need %.0f%%" % (100 * need) if need else "")
        print("  %-4s %-8s %s: %s %s  limit %s %s  margin %s %s%s" % (
            "pass" if ok else "FAIL", ident, what, fmt % value, unit, kind, fmt % limit,
            fmt % margin, unit, rel))
        if not ok:
            self.failed.append(ident)
        return ok

    def info(self, what, text):
        print("  info %s: %s" % (what, text))

    def done(self):
        if self.failed:
            print("FAILED: %s" % " ".join(self.failed))
            return 1
        print("all checks pass")
        return 0
