#!/usr/bin/env python3
"""CPU-004..007: assemble test/cpu/directed.s, hand its labels to
soc/tb/tb_cpu_directed.vhd as a generated package, and run one section.

    python3 tools/cpudirected.py CPU-005
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build", "cpu_directed")


def main():
    section = sys.argv[1] if len(sys.argv) > 1 else "all"
    os.makedirs(BUILD, exist_ok=True)
    src = os.path.join(ROOT, "test", "cpu", "directed.s")
    obj = os.path.join(BUILD, "directed.o")
    mapf = os.path.join(BUILD, "directed.map")
    subprocess.run([sys.executable, os.path.join(ROOT, "tools", "as.py"), src, obj,
                    "0x1000,0x3000,0x5000", "--map=" + mapf], check=True, capture_output=True, cwd=BUILD)

    syms = {}
    for ln in open(mapf):
        t = ln.split()
        if t[0] == "sym" and "." not in t[2]:
            syms[t[2]] = int(t[1], 16)
    pkg = ["-- generated by tools/cpudirected.py from test/cpu/directed.s", "package cpu_directed_syms is"]
    pkg += ["\tconstant L_%s: natural := 16#%04x#;" % (k, v) for k, v in sorted(syms.items())]
    pkg += ["end package;", ""]
    pkg_path = os.path.join(BUILD, "cpu_directed_syms.vhd")
    text = "\n".join(pkg)
    if not os.path.exists(pkg_path) or open(pkg_path).read() != text:
        with open(pkg_path, "w") as f:
            f.write(text)

    image = open(obj, "rb").read()
    hexf = os.path.join(BUILD, "directed.hex")
    with open(hexf, "w") as f:
        f.write("".join("%02x\n" % b for b in image[:0x2000]))

    files = [os.path.join(ROOT, "soc", n) for n in ("alu.vhd", "cpu.vhd")]
    files += [pkg_path, os.path.join(ROOT, "soc", "tb", "tb_cpu_directed.vhd")]
    r = subprocess.run([os.path.join(ROOT, "soc", "tb", "run_ghdl.sh"), "tb_cpu_directed", *files,
                        "--", "-gIMAGE=" + hexf, "-gONLY=" + section])
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
