#!/usr/bin/env python3
"""Generate doc/hardware/fab-readiness.md: what the verification contract
(doc/hardware/verification.md) says must be green before ordering, and where
each row stands.

    python3 tools/fabready.py          (make verify runs it)

Sources: test/catalogue.toml (which tests cover which row), the last
build/test/results.json from test/run.py, each board's build/hw/<board>/
outputs, and doc/hardware/fab-waivers.md (the decisions and hand checks
written by people, included as they are). The sign-off line is left for David.
"""
import glob
import json
import os
import re
import time
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "doc", "hardware", "fab-readiness.md")


def rows():
    """[(row, artifact)] from verification.md's matrix, in order."""
    out = []
    for line in open(os.path.join(ROOT, "doc", "hardware", "verification.md")):
        m = re.match(r"\|\s*(\d+\.\d+)\s*\|\s*([^|]+?)\s*\|", line)
        if m:
            out.append((m.group(1), re.sub(r"\*\*|`", "", m.group(2))))
    return out


def board_status(script):
    name = os.path.splitext(os.path.basename(script))[0]
    out = os.path.join(ROOT, "build", "hw", name)
    fab = os.path.join(out, "fab")
    src = open(script).read()
    rev = (re.search(r'^REVISION\s*=\s*"([A-Z]+)"', src, re.M)            # REVISION = "A"
           or re.search(r'^\w+,\s*REVISION\s*=\s*"[^"]*",\s*"([A-Z]+)"', src, re.M))   # TITLE, REVISION = "..", "A"
    if not os.path.isdir(fab):
        return name, rev.group(1) if rev else "?", "not built", "", ""
    files = sorted(os.listdir(fab))
    order = {}
    if "order.json" in files:
        order = json.load(open(os.path.join(fab, "order.json")))
    parts = 0
    if "bom.csv" in files:
        parts = max(0, sum(1 for _ in open(os.path.join(fab, "bom.csv"))) - 1)
    built = time.strftime("%Y-%m-%d %H:%M", time.localtime(os.path.getmtime(fab)))
    spec = "%s layers, %s mm, %s" % (order.get("layers", "?"), order.get("thickness_mm", "?"),
                                     order.get("surface_finish", "?"))
    if order.get("gold_fingers"):
        spec += ", %s fingers, %s deg bevel" % (order.get("finger_finish"), order.get("finger_chamfer_deg"))
    newer = os.path.getmtime(script) > os.path.getmtime(fab)
    return (name, rev.group(1) if rev else "?", "built %s%s" % (built, " (script changed since: rebuild)" if newer else ""),
            "%d BOM lines" % parts, spec)


def main():
    with open(os.path.join(ROOT, "test", "catalogue.toml"), "rb") as f:
        tests = tomllib.load(f)["test"]
    res_path = os.path.join(ROOT, "build", "test", "results.json")
    results, when = {}, "never"
    if os.path.exists(res_path):
        r = json.load(open(res_path))
        results = {x["id"]: x["status"] for x in r["results"]}
        when = r["time"]

    lines = ["# Fab readiness (Milestone 1)", "",
             "*Generated by `tools/fabready.py` from the last `make verify` (%s) and the board builds. "
             "Do not edit; edit `fab-waivers.md` for decisions and hand checks.*" % when, "",
             "Nothing is ordered until every row below is green and David has signed off at the bottom "
             "(`verification.md`).", ""]

    lines += ["## Verification rows", "", "| Row | Artifact | Tests | State |", "|---|---|---|---|"]
    all_green = True
    for row, artifact in rows():
        ts = [t for t in tests if str(t.get("vrow")) == row and t["kind"] != "hw"]
        st = [results.get(t["id"], "not run") if t.get("cmd") else "pending" for t in ts]
        if not ts:
            state = "no tests"
        elif all(s == "pass" for s in st):
            state = "green"
        else:
            bad = ["%s %s" % (t["id"], s) for t, s in zip(ts, st) if s != "pass"]
            state = "**red**: " + ", ".join(bad[:6]) + (" (+%d)" % (len(bad) - 6) if len(bad) > 6 else "")
        all_green &= state == "green"
        lines.append("| %s | %s | %d | %s |" % (row, artifact[:60], len(ts), state))
    lines.append("")

    lines += ["## Boards", "", "| Board | Rev | Fab outputs | Parts | Order |", "|---|---|---|---|---|"]
    for script in sorted(glob.glob(os.path.join(ROOT, "hw", "boards", "*.py"))):
        if os.path.basename(script).startswith("_") or "def main" not in open(script).read():
            continue
        lines.append("| %s | %s | %s | %s | %s |" % board_status(script))
    lines.append("")

    waivers = os.path.join(ROOT, "doc", "hardware", "fab-waivers.md")
    if os.path.exists(waivers):
        text = open(waivers).read().strip().split("\n")
        lines += [l for l in text if not l.startswith("# ")] + [""]

    hw = [t for t in tests if t["kind"] == "hw"]
    lines += ["## After delivery", "",
              "%d hardware tests (`kind = \"hw\"`) run on the assembled boards through `cupc8.py`; "
              "they are not part of this gate." % len(hw), ""]

    lines += ["## Sign-off", "",
              "All rows green: **%s**." % ("yes" if all_green else "no"), "",
              "Signed off for ordering by David: ________  date: ________", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.relpath(OUT, ROOT), "- all rows green:", all_green)


if __name__ == "__main__":
    main()
