#!/usr/bin/env python3
"""Generate fw/common/font8x8_cp437.c from dhepper/font8x8 (public domain).

  gen_font.py <font8x8 checkout dir>

font8x8 stores each row with bit 0 = leftmost pixel; the CUPC/8 GPU protocol
uses bit 7 = leftmost, so rows are bit-reversed. Codes $00-$7F come from
font8x8_basic; CP437's box-drawing and shade characters ($B0-$DF) come from
font8x8_box / font8x8_block. Other upper-half codes (accented letters, Greek)
are blank for now.
"""
import os
import re
import sys

# CP437 $B0-$DF → Unicode
CP437_B0 = [0x2591, 0x2592, 0x2593, 0x2502, 0x2524, 0x2561, 0x2562, 0x2556,
            0x2555, 0x2563, 0x2551, 0x2557, 0x255D, 0x255C, 0x255B, 0x2510,
            0x2514, 0x2534, 0x252C, 0x251C, 0x2500, 0x253C, 0x255E, 0x255F,
            0x255A, 0x2554, 0x2569, 0x2566, 0x2560, 0x2550, 0x256C, 0x2567,
            0x2568, 0x2564, 0x2565, 0x2559, 0x2558, 0x2552, 0x2553, 0x256B,
            0x256A, 0x2518, 0x250C, 0x2588, 0x2584, 0x258C, 0x2590, 0x2580]


def parse(path, first):
    """{codepoint: [8 rows]} from one font8x8 header."""
    rows = re.findall(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){7}0x[0-9A-Fa-f]{2})\s*\}", open(path).read())
    return {first + i: [int(v, 16) for v in r.split(",")] for i, r in enumerate(rows)}


def rev(b):
    return int("{:08b}".format(b)[::-1], 2)


def main():
    src = sys.argv[1]
    glyphs = {}
    glyphs.update(parse(os.path.join(src, "font8x8_basic.h"), 0x0000))
    glyphs.update(parse(os.path.join(src, "font8x8_box.h"), 0x2500))
    glyphs.update(parse(os.path.join(src, "font8x8_block.h"), 0x2580))

    table = []
    for code in range(256):
        if code < 0x80:
            g = glyphs.get(code, [0] * 8)
        elif 0xB0 <= code <= 0xDF:
            g = glyphs.get(CP437_B0[code - 0xB0], [0] * 8)
        else:
            g = [0] * 8
        table.append([rev(b) for b in g])

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "fw", "common", "font8x8_cp437.c")
    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_font.py from dhepper/font8x8 (public domain,\n"
                " * derived from the public-domain IBM VGA fonts). Do not edit.\n"
                " * 256 CP437 glyphs, 8 rows each, bit 7 = leftmost pixel. */\n\n"
                "#include \"font8x8_cp437.h\"\n\n"
                "const uint8_t font8x8_cp437[256][8] = {\n")
        for code, g in enumerate(table):
            f.write("\t{%s},\t/* $%02X */\n" % (", ".join("0x%02x" % b for b in g), code))
        f.write("};\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
